# Data Cleaning: U.S. Interest Rates and Housing Market

This notebook cleans the raw interest rate and housing market datasets before combining them for analysis. I standardized column names, converted dates and numeric values to the correct data types, and removed rows with invalid dates where needed.

In [73]:
import pandas as pd
from pathlib import Path

In [74]:
RAW_DATA = Path("../data/raw")
RAW_DATA.exists()

True

In [75]:
list(RAW_DATA.iterdir())

[PosixPath('../data/raw/starts_cust.xlsx'),
 PosixPath('../data/raw/.DS_Store'),
 PosixPath('../data/raw/sold_cust.xlsx'),
 PosixPath('../data/raw/MORTGAGE30US.csv'),
 PosixPath('../data/raw/FEDFUNDS.csv')]

## 1. Cleaning Interest Rate Data

I loaded the federal funds rate and 30-year mortgage rate datasets, checked their structures and data types, converted the date columns, and renamed the columns for consistency.

In [76]:
fed_funds = pd.read_csv(RAW_DATA/ "FEDFUNDS.csv")
mortgage = pd.read_csv(RAW_DATA/ "MORTGAGE30US.csv")

In [77]:
fed_funds.head()

  observation_date  FEDFUNDS
0       1954-07-01      0.80
1       1954-08-01      1.22
2       1954-09-01      1.07
3       1954-10-01      0.85
4       1954-11-01      0.83

In [78]:
fed_funds.shape

(867, 2)

In [79]:
fed_funds.columns

Index(['observation_date', 'FEDFUNDS'], dtype='object')

In [80]:
fed_funds.dtypes

observation_date     object
FEDFUNDS            float64
dtype: object

In [81]:
fed_funds["observation_date"] = pd.to_datetime(
    fed_funds["observation_date"],
    errors="coerce"
)

In [82]:
fed_funds.dtypes

observation_date    datetime64[ns]
FEDFUNDS                   float64
dtype: object

In [83]:
fed_funds.columns = ["date", "fed_funds_rate"]

In [84]:
fed_funds.head()

        date  fed_funds_rate
0 1954-07-01            0.80
1 1954-08-01            1.22
2 1954-09-01            1.07
3 1954-10-01            0.85
4 1954-11-01            0.83

In [85]:
fed_funds.to_csv(
    "../data/processed/fed_funds_clean.csv",
    index=False
)

In [86]:
mortgage.head()

  observation_date  MORTGAGE30US
0       1971-04-01          7.31
1       1971-05-01          7.43
2       1971-06-01          7.53
3       1971-07-01          7.60
4       1971-08-01          7.70

In [87]:
mortgage.shape

(667, 2)

In [88]:
mortgage.columns

Index(['observation_date', 'MORTGAGE30US'], dtype='object')

In [89]:
mortgage.dtypes

observation_date     object
MORTGAGE30US        float64
dtype: object

In [90]:
mortgage["observation_date"] = pd.to_datetime(
    mortgage["observation_date"],
    errors="coerce"
)

In [91]:
mortgage.dtypes

observation_date    datetime64[ns]
MORTGAGE30US               float64
dtype: object

In [92]:
mortgage.columns = ["date", "mortgage_rate"]

In [93]:
mortgage.head()

        date  mortgage_rate
0 1971-04-01           7.31
1 1971-05-01           7.43
2 1971-06-01           7.53
3 1971-07-01           7.60
4 1971-08-01           7.70

In [94]:
mortgage.to_csv(
    "../data/processed/mortgage_clean.csv",
    index=False
)

## 2. Cleaning Housing Starts Data

I selected the seasonally adjusted housing starts data from the Excel workbook, extracted the date and value columns, converted them to the appropriate data types, and removed rows with invalid dates.

In [95]:
housing_starts = pd.read_excel(RAW_DATA/"starts_cust.xlsx")
new_home_sales = pd.read_excel(RAW_DATA/"sold_cust.xlsx")

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [96]:
pd.ExcelFile(RAW_DATA/"starts_cust.xlsx").sheet_names

['Annual',
 'Not Seasonally Adjusted',
 'Seasonally Adjusted',
 'Seasonal Factors']

In [97]:
housing_starts_sa = pd.read_excel(RAW_DATA/"starts_cust.xlsx",sheet_name="Seasonally Adjusted")

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [98]:
housing_starts_sa.head(7)

,New Privately-Owned Housing Units Started,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,(Thousands of units. Detail may not add to to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Seasonally adjusted annual rate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Month,United States,NaN,NaN,NaN,Northeast,NaN,Midwest,NaN,South,NaN,West,NaN
4,NaN,Total,1 unit,2 to 4\n units,5 units\n or more,Total,1 unit,Total,1 unit,Total,1 unit,Total,1 unit
5,1959-01-01 00:00:00,1657,1336,(S),(NA),350,(NA),452,(NA),505,(NA),350,(NA)
6,1959-02-01 00:00:00,1667,1317,(S),(NA),346,(NA),469,(NA),508,(NA),344,(NA)

In [99]:
housing_starts_sa.shape

(826, 13)

In [100]:
housing_starts_sa.columns

Index(['New Privately-Owned Housing Units Started', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12'],
      dtype='object')

In [101]:
housing_starts_sa.dtypes

New Privately-Owned Housing Units Started    object
Unnamed: 1                                   object
Unnamed: 2                                   object
Unnamed: 3                                   object
Unnamed: 4                                   object
Unnamed: 5                                   object
Unnamed: 6                                   object
Unnamed: 7                                   object
Unnamed: 8                                   object
Unnamed: 9                                   object
Unnamed: 10                                  object
Unnamed: 11                                  object
Unnamed: 12                                  object
dtype: object

In [102]:
housing_starts_sa.iloc[5:,[0,1]]

             New Privately-Owned Housing Units Started Unnamed: 1
5                                  1959-01-01 00:00:00       1657
6                                  1959-02-01 00:00:00       1667
7                                  1959-03-01 00:00:00       1620
8                                  1959-04-01 00:00:00       1590
9                                  1959-05-01 00:00:00       1498
..                                                 ...        ...
821                                                NaN        NaN
822  Source:  U.S. Census Bureau and U.S. Departmen...        NaN
823  Additional information on the survey methodolo...        NaN
824                                                NaN        NaN
825  Note:  Through July 1963, the '5 units or more...        NaN

[821 rows x 2 columns]

In [103]:
housing_starts_clean = housing_starts_sa.iloc[5:,[0,1]].copy()

In [104]:
housing_starts_clean.head()

  New Privately-Owned Housing Units Started Unnamed: 1
5                       1959-01-01 00:00:00       1657
6                       1959-02-01 00:00:00       1667
7                       1959-03-01 00:00:00       1620
8                       1959-04-01 00:00:00       1590
9                       1959-05-01 00:00:00       1498

In [105]:
housing_starts_clean.tail()

             New Privately-Owned Housing Units Started Unnamed: 1
821                                                NaN        NaN
822  Source:  U.S. Census Bureau and U.S. Departmen...        NaN
823  Additional information on the survey methodolo...        NaN
824                                                NaN        NaN
825  Note:  Through July 1963, the '5 units or more...        NaN

In [106]:
housing_starts_clean.shape

(821, 2)

In [107]:
housing_starts_sa.iloc[:, 0].dtype

dtype('O')

In [108]:
dates = pd.to_datetime(
    housing_starts_sa.iloc[:, 0],
    errors="coerce"
)

/var/folders/2n/t3vdnyps4h56pf165b741t7w0000gn/T/ipykernel_42734/2033144329.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dates = pd.to_datetime(

In [109]:
dates.tail()

821   NaT
822   NaT
823   NaT
824   NaT
825   NaT
Name: New Privately-Owned Housing Units Started, dtype: datetime64[ns]

In [110]:
valid_rows = dates.notna()
valid_rows.tail()

821    False
822    False
823    False
824    False
825    False
Name: New Privately-Owned Housing Units Started, dtype: bool

In [111]:
housing_starts_clean.loc[
    valid_rows,
    [housing_starts_sa.columns[0],
     housing_starts_clean.columns[1]]
]

    New Privately-Owned Housing Units Started Unnamed: 1
5                         1959-01-01 00:00:00       1657
6                         1959-02-01 00:00:00       1667
7                         1959-03-01 00:00:00       1620
8                         1959-04-01 00:00:00       1590
9                         1959-05-01 00:00:00       1498
..                                        ...        ...
812                       2026-04-01 00:00:00       1414
813                       2026-05-01 00:00:00       1182
814                       2026-06-01 00:00:00       1439
815                       2026-07-01 00:00:00       1309
816                       2026-08-01 00:00:00       1275

[812 rows x 2 columns]

In [112]:
housing_starts_clean.columns = ["date", "housing_starts"]
housing_starts_clean.head()

                  date housing_starts
5  1959-01-01 00:00:00           1657
6  1959-02-01 00:00:00           1667
7  1959-03-01 00:00:00           1620
8  1959-04-01 00:00:00           1590
9  1959-05-01 00:00:00           1498

In [113]:
housing_starts_clean.dtypes

date              object
housing_starts    object
dtype: object

In [114]:
housing_starts_clean["date"] = pd.to_datetime(
    housing_starts_clean["date"],
    errors="coerce"
)

In [115]:
housing_starts_clean.dtypes

date              datetime64[ns]
housing_starts            object
dtype: object

In [116]:
housing_starts_clean["date"].isna().sum()

np.int64(9)

In [117]:
# if there is Nat value, you can use this code
housing_starts_clean = housing_starts_clean[
    housing_starts_clean["date"].notna()
].copy()

In [118]:
housing_starts_clean.shape

(812, 2)

In [119]:
housing_starts_clean.tail()

          date housing_starts
812 2026-04-01           1414
813 2026-05-01           1182
814 2026-06-01           1439
815 2026-07-01           1309
816 2026-08-01           1275

In [120]:
housing_starts_clean["housing_starts"] = pd.to_numeric(
    housing_starts_clean["housing_starts"],
    errors="coerce"
)

In [121]:
housing_starts_clean.dtypes

date              datetime64[ns]
housing_starts             int64
dtype: object

In [122]:
housing_starts_clean.to_csv(
    "../data/processed/housing_starts_clean.csv",
    index=False
)

In [123]:
pd.ExcelFile(RAW_DATA / "sold_cust.xlsx").sheet_names

['Annual', 'Monthly', 'Seasonal Factors']

## 3. Cleaning New Home Sales Data

I selected the monthly new home sales data from the Excel workbook, extracted the relevant date and sales columns, converted them to the correct data types, and checked for missing values.

In [124]:
new_home_sales_monthly = pd.read_excel(
    RAW_DATA/"sold_cust.xlsx",
    sheet_name="Monthly"
)

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

In [125]:
new_home_sales_monthly.head(10)

,New Privately-Owned Houses Sold,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,(Thousands of units. Detail may not add to to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Monthly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Month,Not seasonally adjusted,NaN,NaN,NaN,NaN,Seasonally adjusted annual rate,NaN,NaN,NaN,NaN
4,NaN,United States,Northeast,Midwest,South,West,United States,Northeast,Midwest,South,West
5,1963-01-01 00:00:00,42,(NA),(NA),(NA),(NA),591,(NA),(NA),(NA),(NA)
6,1963-02-01 00:00:00,35,(NA),(NA),(NA),(NA),464,(NA),(NA),(NA),(NA)
7,1963-03-01 00:00:00,44,(NA),(NA),(NA),(NA),461,(NA),(NA),(NA),(NA)
8,1963-04-01 00:00:00,52,(NA),(NA),(NA),(NA),605,(NA),(NA),(NA),(NA)
9,1963-05-01 00:00:00,58,(NA),(NA),(NA),(NA),586,(NA),(NA),(NA),(NA)

In [126]:
new_home_sales_monthly.shape

(776, 11)

In [127]:
new_home_sales_clean = new_home_sales_monthly.iloc[5:,[0,6]]
new_home_sales_clean.head()

  New Privately-Owned Houses Sold Unnamed: 6
5             1963-01-01 00:00:00        591
6             1963-02-01 00:00:00        464
7             1963-03-01 00:00:00        461
8             1963-04-01 00:00:00        605
9             1963-05-01 00:00:00        586

In [128]:
data = pd.to_datetime(
    new_home_sales_clean.iloc[:, 0],
    errors="coerce"
)

In [129]:
valid_rows = data.notna()
valid_rows.tail()

771    False
772    False
773    False
774    False
775    False
Name: New Privately-Owned Houses Sold, dtype: bool

In [130]:
new_home_sales_clean = new_home_sales_clean.loc[
    valid_rows,
    [new_home_sales_clean.columns[0],
    new_home_sales_clean.columns[1]
    ]
].copy()

In [131]:
new_home_sales_clean.columns = ["date", "new_home_sales"]
new_home_sales_clean.tail()

                    date new_home_sales
764  2026-04-01 00:00:00            641
765  2026-05-01 00:00:00            636
766  2026-06-01 00:00:00            672
767  2026-07-01 00:00:00            643
768  2026-08-01 00:00:00            684

In [132]:
new_home_sales_clean.dtypes

date              object
new_home_sales    object
dtype: object

In [133]:
new_home_sales_clean["date"] = pd.to_datetime(
    new_home_sales_clean["date"],
    errors="coerce"
)

In [134]:
new_home_sales_clean.dtypes

date              datetime64[ns]
new_home_sales            object
dtype: object

In [135]:
new_home_sales_clean["date"].isna().sum()

np.int64(0)

In [136]:
new_home_sales_clean.shape

(764, 2)

In [137]:
new_home_sales_clean["new_home_sales"] = pd.to_numeric(
    new_home_sales_clean["new_home_sales"],
    errors="coerce"
)

In [138]:
new_home_sales_clean.dtypes

date              datetime64[ns]
new_home_sales             int64
dtype: object

In [139]:
new_home_sales_clean["new_home_sales"].isna().sum()

np.int64(0)

In [140]:
new_home_sales_clean.to_csv(
    "../data/processed/new_home_sales_clean.csv",
    index=False
)

## Cleaning Summary

The four datasets are now saved as separate cleaned CSV files in the processed data folder. These files can be used in the next step to combine the data by date.

The housing starts and new home sales figures are reported in thousands at seasonally adjusted annual rates (SAAR).